// priority: 100

StartupEvents.postInit(e => {
    global.BLOCKSWAP_CONFIG = {
        __comment: 'This config was autogenerated from starter_scripts/_core/block_swap.js',
        generate_all_known_states: false,
        retro_gen: false,
        state_swapper: [],
        swapper: new Map()  // its a map because objects can't have regex as their keys
    }

    global.SWAPPER = new Map()
})

function processBlockswapConfig() {
    // Processing regex keys and turning the map into an object
    let swapperObj = {}
    global.BLOCKSWAP_CONFIG.swapper.forEach((value, key, map) => {
        if (key instanceof RegExp) {
            Ingredient.of(key).itemIds.forEach(match => {
                if (Item.of(match).isBlock()) swapperObj[match] = value
            })
        } else {
            swapperObj[key] = value
        }
    })
    global.BLOCKSWAP_CONFIG.swapper = swapperObj

    JsonIO.write('config/blockswap/block_swap.json5', global.BLOCKSWAP_CONFIG)
}


function processSwapper() {
    global.SWAPPER.forEach((value, key, map) => {
        if (key instanceof RegExp) {
            Ingredient.of(key).itemIds.forEach(match => global.SWAPPER.set(match, value))
            global.SWAPPER.delete(key)
        }
    })
}